return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   ---@class PluginLspOpts
  --   opts = {
  --     ---@type lspconfig.options
  --     servers = {
  --       tsserver = {},
  --     },
  --   },
  -- },
  -- -- add more treesitter parsers
  --  {
  --    "nvim-treesitter/nvim-treesitter",
  --    opts = {
  --      ensure_installed = {
  --        "bash",
  --        "html",
  --        "javascript",
  --        "json",
  --        "lua",
  --        "markdown",
  --        "markdown_inline",
  --        "python",
  --        "query",
  --        "regex",
  --        "tsx",
  --        "typescript",
  --        "vim",
  --        "yaml",
  --      },
  --    },
  -- },
  -- add any tools you want to have installed below
  -- {
  --   "williamboman/mason.nvim",
  --   opts = {
  --     ensure_installed = {
  --       "stylua",
  --       "shellcheck",
  --       "shfmt",
  --       "flake8",
  --     },
  --   },
  -- },
}
